using System;
using System.Collections.Generic;
using System.Linq;
using System.Drawing.Imaging;

namespace QuanLyCLB.Exif
{
    /// <summary>
    /// Provides utility to read EXIF tags in image files
    /// </summary>
    public class PropertyItemReader
    {
        private Dictionary<int, ExifTag> PropertyItemsDict;
        private ConversionConstants constants;

        public PropertyItemReader()
        {
            constants = new ConversionConstants();
            PropertyItemsDict = new Dictionary<int, ExifTag>
            {
                [0x0001] = new ExifTag("InteropIndex"),
                [0x0002] = new ExifTag("InteropVersion"),
                [0x000b] = new ExifTag("Phần mềm xử lý"),
                [0x00fe] = new ExifTag("SubfileType"),
                [0x00ff] = new ExifTag("OldSubfileType"),
                [0x0100] = new ExifTag("Chiều dài hình ảnh"),
                [0x0101] = new ExifTag("Chiều rộng hình ảnh"),
                [0x0102] = new ExifTag("BitsPerSample"),
                [0x0103] = new ExifTag("Nén"),
                [0x0106] = new ExifTag("PhotometricInterpretation"),
                [0x0107] = new ExifTag("Thresholding"),
                [0x0108] = new ExifTag("CellWidth"),
                [0x0109] = new ExifTag("CellLength"),
                [0x010a] = new ExifTag("FillOrder"),
                [0x010d] = new ExifTag("DocumentName"),
                [0x010e] = new ExifTag("Mô tả hình ảnh"),
                [0x010f] = new ExifTag("Hãng máy ảnh"),
                [0x0110] = new ExifTag("Mẫu mã máy ảnh"),
                [0x0111] = new ExifTag("StripOffsets"),
                [0x0112] = new ExifTag<ushort>("Hướng xoay", constants.Orientation),
                [0x0115] = new ExifTag("SamplesPerPixel"),
                [0x0116] = new ExifTag("RowsPerStrip"),
                [0x0117] = new ExifTag("StripByteCounts"),
                [0x0118] = new ExifTag("MinSampleValue"),
                [0x0119] = new ExifTag("MaxSampleValue"),
                [0x011a] = new ExifTag<Rational>("Mật độ phân giải ngang", constants.ToFloatConverter),
                [0x011b] = new ExifTag<Rational>("Mật độ phân giải dọc", constants.ToFloatConverter),
                [0x011c] = new ExifTag("PlanarConfiguration"),
                [0x011d] = new ExifTag("PageName"),
                [0x011e] = new ExifTag("XPosition"),
                [0x011f] = new ExifTag("YPosition"),
                [0x0120] = new ExifTag("FreeOffsets"),
                [0x0121] = new ExifTag("FreeByteCounts"),
                [0x0122] = new ExifTag("GrayResponseUnit"),
                [0x0123] = new ExifTag("GrayResponseCurve"),
                [0x0124] = new ExifTag("T4Options"),
                [0x0125] = new ExifTag("T6Options"),
                [0x0128] = new ExifTag<ushort>("Đơn vị mật độ phân giải", constants.ResolutionUnit),
                [0x0129] = new ExifTag("PageNumber"),
                [0x012c] = new ExifTag("ColorResponseUnit"),
                [0x012d] = new ExifTag("TransferFunction"),
                [0x0131] = new ExifTag("Phần mềm"),
                [0x0132] = new ExifTag<string>("Ngày chỉnh sửa", constants.DateTimeConverter),
                [0x013b] = new ExifTag("Tác giả"),
                [0x013c] = new ExifTag("HostComputer"),
                [0x013d] = new ExifTag("Predictor"),
                [0x013e] = new ExifTag("WhitePoint"),
                [0x013f] = new ExifTag("PrimaryChromaticities"),
                [0x0140] = new ExifTag("ColorMap"),
                [0x0141] = new ExifTag("HalftoneHints"),
                [0x0142] = new ExifTag("TileWidth"),
                [0x0143] = new ExifTag("TileLength"),
                [0x0144] = new ExifTag("TileOffsets"),
                [0x0145] = new ExifTag("TileByteCounts"),
                [0x0146] = new ExifTag("BadFaxLines"),
                [0x0147] = new ExifTag("CleanFaxData"),
                [0x0148] = new ExifTag("ConsecutiveBadFaxLines"),
                [0x014a] = new ExifTag("SubIFD"),
                [0x014c] = new ExifTag("InkSet"),
                [0x014d] = new ExifTag("InkNames"),
                [0x014e] = new ExifTag("NumberofInks"),
                [0x0150] = new ExifTag("DotRange"),
                [0x0151] = new ExifTag("TargetPrinter"),
                [0x0152] = new ExifTag("ExtraSamples"),
                [0x0153] = new ExifTag("SampleFormat"),
                [0x0154] = new ExifTag("SMinSampleValue"),
                [0x0155] = new ExifTag("SMaxSampleValue"),
                [0x0156] = new ExifTag("TransferRange"),
                [0x0157] = new ExifTag("ClipPath"),
                [0x0158] = new ExifTag("XClipPathUnits"),
                [0x0159] = new ExifTag("YClipPathUnits"),
                [0x015a] = new ExifTag("Indexed"),
                [0x015b] = new ExifTag("JPEGTables"),
                [0x015f] = new ExifTag("OPIProxy"),
                [0x0190] = new ExifTag("GlobalParametersIFD"),
                [0x0191] = new ExifTag("ProfileType"),
                [0x0192] = new ExifTag("FaxProfile"),
                [0x0193] = new ExifTag("CodingMethods"),
                [0x0194] = new ExifTag("VersionYear"),
                [0x0195] = new ExifTag("ModeNumber"),
                [0x01b1] = new ExifTag("Decode"),
                [0x01b2] = new ExifTag("DefaultImageColor"),
                [0x01b3] = new ExifTag("T82Options"),
                [0x01b5] = new ExifTag("JPEGTables"),
                [0x0200] = new ExifTag("JPEGProc"),
                [0x0201] = new ExifTag("ThumbnailOffset"),
                [0x0202] = new ExifTag("ThumbnailLength"),
                [0x0203] = new ExifTag("JPEGRestartInterval"),
                [0x0205] = new ExifTag("JPEGLosslessPredictors"),
                [0x0206] = new ExifTag("JPEGPointTransforms"),
                [0x0207] = new ExifTag("JPEGQTables"),
                [0x0208] = new ExifTag("JPEGDCTables"),
                [0x0209] = new ExifTag("JPEGACTables"),
                [0x0211] = new ExifTag("YCbCrCoefficients"),
                [0x0212] = new ExifTag("Lấy mẫu phụ YCbCr"),
                [0x0213] = new ExifTag("YCbCrPositioning"),
                [0x0214] = new ExifTag("ReferenceBlackWhite"),
                [0x022f] = new ExifTag("StripRowCounts"),
                [0x02bc] = new ExifTag("ApplicationNotes"),
                [0x0303] = new ExifTag("RenderingIntent"),
                [0x03e7] = new ExifTag("USPTOMiscellaneous"),
                [0x1000] = new ExifTag("RelatedImageFileFormat"),
                [0x1001] = new ExifTag("RelatedImageWidth"),
                [0x1002] = new ExifTag("RelatedImageHeight"),
                [0x4746] = new ExifTag("Rating"),
                [0x4747] = new ExifTag("XP_DIP_XML"),
                [0x4748] = new ExifTag("StitchInfo"),
                [0x4749] = new ExifTag("RatingPercent"),
                [0x5001] = new ExifTag("ResolutionXUnit"),
                [0x5002] = new ExifTag("ResolutionYUnit"),
                [0x5003] = new ExifTag("ResolutionXLengthUnit"),
                [0x5004] = new ExifTag("ResolutionYLengthUnit"),
                [0x5005] = new ExifTag("PrintFlags"),
                [0x5006] = new ExifTag("PrintFlagsVersion"),
                [0x5007] = new ExifTag("PrintFlagsCrop"),
                [0x5008] = new ExifTag("PrintFlagsBleedWidth"),
                [0x5009] = new ExifTag("PrintFlagsBleedWidthScale"),
                [0x500a] = new ExifTag("HalftoneLPI"),
                [0x500b] = new ExifTag("HalftoneLPIUnit"),
                [0x500c] = new ExifTag("HalftoneDegree"),
                [0x500d] = new ExifTag("HalftoneShape"),
                [0x500e] = new ExifTag("HalftoneMisc"),
                [0x500f] = new ExifTag("HalftoneScreen"),
                [0x5010] = new ExifTag("JPEGQuality"),
                [0x5011] = new ExifTag("GridSize"),
                [0x5012] = new ExifTag("ThumbnailFormat"),
                [0x5013] = new ExifTag("ThumbnailWidth"),
                [0x5014] = new ExifTag("ThumbnailHeight"),
                [0x5015] = new ExifTag("ThumbnailColorDepth"),
                [0x5016] = new ExifTag("ThumbnailPlanes"),
                [0x5017] = new ExifTag("ThumbnailRawBytes"),
                [0x5018] = new ExifTag("ThumbnailLength"),
                [0x5019] = new ExifTag("ThumbnailCompressedSize"),
                [0x501a] = new ExifTag("ColorTransferFunction"),
                [0x501b] = new ExifTag("ThumbnailData"),
                [0x5020] = new ExifTag("ThumbnailImageWidth"),
                [0x5021] = new ExifTag("ThumbnailImageHeight"),
                [0x5022] = new ExifTag("ThumbnailBitsPerSample"),
                [0x5023] = new ExifTag("ThumbnailCompression"),
                [0x5024] = new ExifTag("ThumbnailPhotometricInterp"),
                [0x5025] = new ExifTag("Mô tả thumbnail"),
                [0x5026] = new ExifTag("Hãng máy ảnh của thumbnail"),
                [0x5027] = new ExifTag("Mẫu mã máy ảnh của thumbnail"),
                [0x5028] = new ExifTag("ThumbnailStripOffsets"),
                [0x5029] = new ExifTag("Hướng xoay thumbnail"),
                [0x502a] = new ExifTag("ThumbnailSamplesPerPixel"),
                [0x502b] = new ExifTag("ThumbnailRowsPerStrip"),
                [0x502c] = new ExifTag("ThumbnailStripByteCounts"),
                [0x502d] = new ExifTag("Mật độ điểm ảnh ngang thumbnail"),
                [0x502e] = new ExifTag("Mật độ điểm ảnh dọc thumbnail"),
                [0x502f] = new ExifTag("ThumbnailPlanarConfig"),
                [0x5030] = new ExifTag("Đơn vị mật độ điểm ảnh thumbnail"),
                [0x5031] = new ExifTag("ThumbnailTransferFunction"),
                [0x5032] = new ExifTag("Phần mềm thumbnail"),
                [0x5033] = new ExifTag<string>("ThumbnailDateTime", constants.DateTimeConverter),
                [0x5034] = new ExifTag("Tác giả thumbnail"),
                [0x5035] = new ExifTag("Điểm trắng thumbnail"),
                [0x5036] = new ExifTag("ThumbnailPrimaryChromaticities"),
                [0x5037] = new ExifTag("ThumbnailYCbCrCoefficients"),
                [0x5038] = new ExifTag("Lấy mẫu phụ YCbCr thumbnail"),
                [0x5039] = new ExifTag("ThumbnailYCbCrPositioning"),
                [0x503a] = new ExifTag("ThumbnailRefBlackWhite"),
                [0x503b] = new ExifTag("Bản quyền thumbnail"),
                [0x5090] = new ExifTag("Bảng độ sáng"),
                [0x5091] = new ExifTag("Bảng thành phần màu"),
                [0x5100] = new ExifTag("FrameDelay"),
                [0x5101] = new ExifTag("Số lần lặp"),
                [0x5102] = new ExifTag("GlobalPalette"),
                [0x5103] = new ExifTag("IndexBackground"),
                [0x5104] = new ExifTag("IndexTransparent"),
                [0x5110] = new ExifTag("PixelUnits"),
                [0x5111] = new ExifTag("PixelsPerUnitX"),
                [0x5112] = new ExifTag("PixelsPerUnitY"),
                [0x5113] = new ExifTag("PaletteHistogram"),
                [0x7000] = new ExifTag("SonyRawFileType"),
                [0x7010] = new ExifTag("SonyToneCurve"),
                [0x7031] = new ExifTag("VignettingCorrection"),
                [0x7032] = new ExifTag("VignettingCorrParams"),
                [0x7034] = new ExifTag("ChromaticAberrationCorrection"),
                [0x7035] = new ExifTag("ChromaticAberrationCorrParams"),
                [0x7036] = new ExifTag("DistortionCorrection"),
                [0x7037] = new ExifTag("DistortionCorrParams"),
                [0x7038] = new ExifTag("SonyRawImageSize"),
                [0x7310] = new ExifTag("BlackLevel"),
                [0x7313] = new ExifTag("WB_RGGBLevels"),
                [0x74c7] = new ExifTag("SonyCropTopLeft"),
                [0x74c8] = new ExifTag("SonyCropSize"),
                [0x800d] = new ExifTag("Mã hình ảnh"),
                [0x80a3] = new ExifTag("WangTag1"),
                [0x80a4] = new ExifTag("WangAnnotation"),
                [0x80a5] = new ExifTag("WangTag3"),
                [0x80a6] = new ExifTag("WangTag4"),
                [0x80b9] = new ExifTag("ImageReferencePoints"),
                [0x80ba] = new ExifTag("RegionXformTackPoint"),
                [0x80bb] = new ExifTag("WarpQuadrilateral"),
                [0x80bc] = new ExifTag("AffineTransformMat"),
                [0x80e3] = new ExifTag("Matteing"),
                [0x80e4] = new ExifTag("Kiểu dữ liệu"),
                [0x80e5] = new ExifTag("ImageDepth"),
                [0x80e6] = new ExifTag("TileDepth"),
                [0x8214] = new ExifTag("ImageFullWidth"),
                [0x8215] = new ExifTag("ImageFullHeight"),
                [0x8216] = new ExifTag("TextureFormat"),
                [0x8217] = new ExifTag("WrapModes"),
                [0x8218] = new ExifTag("FovCot"),
                [0x8219] = new ExifTag("MatrixWorldToScreen"),
                [0x821a] = new ExifTag("MatrixWorldToCamera"),
                [0x827d] = new ExifTag("Model2"),
                [0x828d] = new ExifTag("CFARepeatPatternDim"),
                [0x828e] = new ExifTag("CFAPattern2"),
                [0x828f] = new ExifTag("Mức pin"),
                [0x8290] = new ExifTag("KodakIFD"),
                [0x8298] = new ExifTag("Bản quyền"),
                [0x829a] = new ExifTag("Tốc độ màn trập"),
                [0x829d] = new ExifTag<Rational>("Khẩu độ", constants.FNumberConverter),
                [0x82a5] = new ExifTag("MDFileTag"),
                [0x82a6] = new ExifTag("MDScalePixel"),
                [0x82a7] = new ExifTag("MDColorTable"),
                [0x82a8] = new ExifTag("MDLabName"),
                [0x82a9] = new ExifTag("MDSampleInfo"),
                [0x82aa] = new ExifTag("MDPrepDate"),
                [0x82ab] = new ExifTag("MDPrepTime"),
                [0x82ac] = new ExifTag("MDFileUnits"),
                [0x830e] = new ExifTag("PixelScale"),
                [0x8335] = new ExifTag("AdventScale"),
                [0x8336] = new ExifTag("AdventRevision"),
                [0x835c] = new ExifTag("UIC1Tag"),
                [0x835d] = new ExifTag("UIC2Tag"),
                [0x835e] = new ExifTag("UIC3Tag"),
                [0x835f] = new ExifTag("UIC4Tag"),
                [0x83bb] = new ExifTag("IPTC-NAA"),
                [0x847e] = new ExifTag("IntergraphPacketData"),
                [0x847f] = new ExifTag("IntergraphFlagRegisters"),
                [0x8480] = new ExifTag("IntergraphMatrix"),
                [0x8481] = new ExifTag("INGRReserved"),
                [0x8482] = new ExifTag("ModelTiePoint"),
                [0x84e0] = new ExifTag("Site"),
                [0x84e1] = new ExifTag("Dãy màu"),
                [0x84e2] = new ExifTag("IT8Header"),
                [0x84e3] = new ExifTag("RasterPadding"),
                [0x84e4] = new ExifTag("BitsPerRunLength"),
                [0x84e5] = new ExifTag("BitsPerExtendedRunLength"),
                [0x84e6] = new ExifTag("Bảng màu"),
                [0x84e7] = new ExifTag("ImageColorIndicator"),
                [0x84e8] = new ExifTag("BackgroundColorIndicator"),
                [0x84e9] = new ExifTag("Giá trị màu hình"),
                [0x84ea] = new ExifTag("Giá trị màu nền"),
                [0x84eb] = new ExifTag("PixelIntensityRange"),
                [0x84ec] = new ExifTag("TransparencyIndicator"),
                [0x84ed] = new ExifTag("ColorCharacterization"),
                [0x84ee] = new ExifTag<ushort>("HCUsage", constants.HCUsage),
                [0x84ef] = new ExifTag("TrapIndicator"),
                [0x84f0] = new ExifTag("CMYK tương đương"),
                [0x8546] = new ExifTag("SEMInfo"),
                [0x8568] = new ExifTag("AFCP_IPTC"),
                [0x85b8] = new ExifTag("PixelMagicJBIGOptions"),
                [0x85d7] = new ExifTag("JPLCartoIFD"),
                [0x85d8] = new ExifTag("ModelTransform"),
                [0x8602] = new ExifTag("WB_GRGBLevels"),
                [0x8606] = new ExifTag("LeafData"),
                [0x8649] = new ExifTag("Tuỳ chỉnh Photoshop"),
                [0x8769] = new ExifTag("ExifOffset"),
                [0x8773] = new ExifTag("ICC_Profile"),
                [0x877f] = new ExifTag("TIFF_FXExtensions"),
                [0x8780] = new ExifTag("Đa hồ sơ"),
                [0x8781] = new ExifTag("Dữ liệu được chia sẻ"),
                [0x8782] = new ExifTag("Tuỳ chỉnh T88"),
                [0x87ac] = new ExifTag("Lớp hình"),
                [0x87af] = new ExifTag("GeoTiffDirectory"),
                [0x87b0] = new ExifTag("GeoTiffDoubleParams"),
                [0x87b1] = new ExifTag("GeoTiffAsciiParams"),
                [0x87be] = new ExifTag("Tuỳ chỉnh JBIG"),
                [0x8822] = new ExifTag<ushort>("Chương trình phơi sáng", constants.ExposureProgram),
                [0x8824] = new ExifTag("Độ nhạy quang phổ"),
                [0x8825] = new ExifTag("Thông tin GPS"),
                [0x8827] = new ExifTag("ISO"),
                [0x8828] = new ExifTag("Opto-ElectricConvFactor"),
                [0x8829] = new ExifTag("Interlace"),
                [0x882a] = new ExifTag("Độ lệch múi giờ"),
                [0x882b] = new ExifTag("Chế độ tự đếm giờ"),
                [0x8830] = new ExifTag<ushort>("Kiểu nhạy", constants.SensitivityType),
                [0x8831] = new ExifTag("Độ nhạy đầu ra chuẩn"),
                [0x8832] = new ExifTag("Chỉ số phơi sáng khuyến nghị"),
                [0x8833] = new ExifTag("Tốc độ ISO"),
                [0x8834] = new ExifTag("ISOSpeedLatitudeyyy"),
                [0x8835] = new ExifTag("ISOSpeedLatitudezzz"),
                [0x885c] = new ExifTag("FaxRecvParams"),
                [0x885d] = new ExifTag("FaxSubAddress"),
                [0x885e] = new ExifTag("FaxRecvTime"),
                [0x8871] = new ExifTag("FedexEDR"),
                [0x888a] = new ExifTag("LeafSubIFD"),
                [0x9000] = new ExifTag<byte>("Phiên bản EXIF", constants.VersionConverter),
                [0x9003] = new ExifTag<string>("DateTimeOriginal", constants.DateTimeConverter),
                [0x9004] = new ExifTag<string>("Ngày tạo", constants.DateTimeConverter),
                [0x9009] = new ExifTag("Mã tải lên Google Plus"),
                [0x9010] = new ExifTag("OffsetTime"),
                [0x9011] = new ExifTag("OffsetTimeOriginal"),
                [0x9012] = new ExifTag("OffsetTimeDigitized"),
                [0x9101] = new ExifTag("ComponentsConfiguration"),
                [0x9102] = new ExifTag("Số bit được nén mỗi pixel"),
                [0x9201] = new ExifTag("Giá trị tốc độ màn trập"),
                [0x9202] = new ExifTag("Giá trị khẩu độ"),
                [0x9203] = new ExifTag("Giá trị độ sáng"),
                [0x9204] = new ExifTag("Bù trừ phơi sáng"),
                [0x9205] = new ExifTag("Giá trị khẩu độ tối đa"),
                [0x9206] = new ExifTag("Khoảng cách chủ thể"),
                [0x9207] = new ExifTag<ushort>("Chế độ đo sáng", constants.ExifMeteringMode),
                [0x9208] = new ExifTag<ushort>("ExifLightSource", constants.ExifLightSource),
                [0x9209] = new ExifTag<ushort>("Đèn flash", constants.Flash),
                [0x920a] = new ExifTag<Rational>("Tiêu cự", constants.FocalLengthConverter),
                [0x920b] = new ExifTag("FlashEnergy"),
                [0x920c] = new ExifTag("SpatialFrequencyResponse"),
                [0x920d] = new ExifTag("Noise"),
                [0x920e] = new ExifTag("FocalPlaneXResolution"),
                [0x920f] = new ExifTag("FocalPlaneYResolution"),
                [0x9210] = new ExifTag<ushort>("FocalPlaneResolutionUnit", constants.FocalPlaneResolutionUnit),
                [0x9211] = new ExifTag("ImageNumber"),
                [0x9212] = new ExifTag("SecurityClassification"),
                [0x9213] = new ExifTag("ImageHistory"),
                [0x9214] = new ExifTag("SubjectArea"),
                [0x9215] = new ExifTag("ExposureIndex"),
                [0x9216] = new ExifTag("TIFF-EPStandardID"),
                [0x9217] = new ExifTag("SensingMethod"),
                [0x923a] = new ExifTag("CIP3DataFile"),
                [0x923b] = new ExifTag("CIP3Sheet"),
                [0x923c] = new ExifTag("CIP3Side"),
                [0x923f] = new ExifTag("StoNits"),
                [0x927c] = new ExifTag<byte>("MakerNoteApple", constants.BinaryDataConverter),
                [0x9286] = new ExifTag<byte>("UserComment", constants.BinaryDataConverter),
                [0x9290] = new ExifTag("SubSecTime"),
                [0x9291] = new ExifTag("SubSecTimeOriginal"),
                [0x9292] = new ExifTag("SubSecTimeDigitized"),
                [0x932f] = new ExifTag("MSDocumentText"),
                [0x9330] = new ExifTag("MSPropertySetStorage"),
                [0x9331] = new ExifTag("MSDocumentTextPosition"),
                [0x935c] = new ExifTag("ImageSourceData"),
                [0x9400] = new ExifTag("AmbientTemperature"),
                [0x9401] = new ExifTag("Humidity"),
                [0x9402] = new ExifTag("Pressure"),
                [0x9403] = new ExifTag("WaterDepth"),
                [0x9404] = new ExifTag("Acceleration"),
                [0x9405] = new ExifTag("CameraElevationAngle"),
                [0x9999] = new ExifTag("XiaomiSettings"),
                [0x9a00] = new ExifTag("XiaomiModel"),
                [0x9c9b] = new ExifTag("XPTitle"),
                [0x9c9c] = new ExifTag("XPComment"),
                [0x9c9d] = new ExifTag("XPAuthor"),
                [0x9c9e] = new ExifTag("XPKeywords"),
                [0x9c9f] = new ExifTag("XPSubject"),
                [0xa000] = new ExifTag<byte>("Phiên bản Flashpix", constants.VersionConverter),
                [0xa001] = new ExifTag<ushort>("Không gian màu", constants.ExifColorSpace),
                [0xa002] = new ExifTag("ExifImageWidth"),
                [0xa003] = new ExifTag("ExifImageHeight"),
                [0xa004] = new ExifTag("RelatedSoundFile"),
                [0xa005] = new ExifTag("InteropOffset"),
                [0xa010] = new ExifTag("SamsungRawPointersOffset"),
                [0xa011] = new ExifTag("SamsungRawPointersLength"),
                [0xa101] = new ExifTag("SamsungRawByteOrder"),
                [0xa102] = new ExifTag("SamsungRawUnknown"),
                [0xa20b] = new ExifTag("FlashEnergy"),
                [0xa20c] = new ExifTag("SpatialFrequencyResponse"),
                [0xa20d] = new ExifTag("Noise"),
                [0xa20e] = new ExifTag("Mật độ điểm ảnh ngang mặt phẳng tiêu"),
                [0xa20f] = new ExifTag("Mật độ điểm ảnh dọc mặt phẳng tiêu"),
                [0xa210] = new ExifTag<ushort>("Đơn vị mật độ điểm ảnh mặt phẳng tiêu", constants.FocalPlaneResolutionUnit),
                [0xa211] = new ExifTag("ImageNumber"),
                [0xa212] = new ExifTag("SecurityClassification"),
                [0xa213] = new ExifTag("ImageHistory"),
                [0xa214] = new ExifTag("SubjectLocation"),
                [0xa215] = new ExifTag("ExposureIndex"),
                [0xa216] = new ExifTag("TIFF-EPStandardID"),
                [0xa217] = new ExifTag<ushort>("SensingMethod", constants.ExifSensingMethod),
                [0xa300] = new ExifTag("FileSource"),
                [0xa301] = new ExifTag("SceneType"),
                [0xa302] = new ExifTag("CFAPattern"),
                [0xa401] = new ExifTag<ushort>("CustomRendered", constants.CustomRendered),
                [0xa402] = new ExifTag<ushort>("Chế độ phơi sáng", constants.ExposureMode),
                [0xa403] = new ExifTag<ushort>("Cân bằng trắng", constants.WhiteBalance),
                [0xa404] = new ExifTag("DigitalZoomRatio"),
                [0xa405] = new ExifTag("FocalLengthIn35mmFormat"),
                [0xa406] = new ExifTag<ushort>("SceneCaptureType", constants.SceneCaptureType),
                [0xa407] = new ExifTag<ushort>("GainControl", constants.GainControl),
                [0xa408] = new ExifTag<ushort>("Độ tương phản", constants.Contrast),
                [0xa409] = new ExifTag<ushort>("Độ bão hoà", constants.Saturation),
                [0xa40a] = new ExifTag<ushort>("Độ nét", constants.Sharpness),
                [0xa40b] = new ExifTag("DeviceSettingDescription"),
                [0xa40c] = new ExifTag<ushort>("SubjectDistanceRange", constants.SubjectDistanceRange),
                [0xa420] = new ExifTag("ImageUniqueID"),
                [0xa430] = new ExifTag("OwnerName"),
                [0xa431] = new ExifTag("Số seri"),
                [0xa432] = new ExifTag("LensInfo"),
                [0xa433] = new ExifTag("Hãng ống kính"),
                [0xa434] = new ExifTag("Mẫu mã ống kính"),
                [0xa435] = new ExifTag("Số seri ống kính"),
                [0xa436] = new ExifTag("ImageTitle"),
                [0xa437] = new ExifTag("Photographer"),
                [0xa438] = new ExifTag("Trình sửa ảnh"),
                [0xa439] = new ExifTag("CameraFirmware"),
                [0xa43a] = new ExifTag("RAWDevelopingSoftware"),
                [0xa43b] = new ExifTag("Phần mềm chỉnh sửa ảnh"),
                [0xa43c] = new ExifTag("MetadataEditingSoftware"),
                [0xa460] = new ExifTag<ushort>("CompositeImage", constants.CompositeImage),
                [0xa461] = new ExifTag("CompositeImageCount"),
                [0xa462] = new ExifTag("CompositeImageExposureTimes"),
                [0xa480] = new ExifTag("GDALMetadata"),
                [0xa481] = new ExifTag("GDALNoData"),
                [0xa500] = new ExifTag("Gamma", obj => ((Rational)obj).ValueOf().ToString("f2")),
                [0xafc0] = new ExifTag("ExpandSoftware"),
                [0xafc1] = new ExifTag("ExpandLens"),
                [0xafc2] = new ExifTag("ExpandFilm"),
                [0xafc3] = new ExifTag("ExpandFilterLens"),
                [0xafc4] = new ExifTag("ExpandScanner"),
                [0xafc5] = new ExifTag("ExpandFlashLamp"),
                [0xb4c3] = new ExifTag("HasselbladRawImage"),
                [0xbc01] = new ExifTag<ushort>("Định dạng pixel", constants.PixelFormat),
                [0xbc02] = new ExifTag<ushort>("Transformation", constants.Transformation),
                [0xbc03] = new ExifTag<ushort>("Uncompressed", constants.Uncompressed),
                [0xbc04] = new ExifTag("ImageType"),
                [0xbc80] = new ExifTag("Chiều dài hình ảnh"),
                [0xbc81] = new ExifTag("Chiều rộng hình ảnh"),
                [0xbc82] = new ExifTag("WidthResolution"),
                [0xbc83] = new ExifTag("HeightResolution"),
                [0xbcc0] = new ExifTag("ImageOffset"),
                [0xbcc1] = new ExifTag("ImageByteCount"),
                [0xbcc2] = new ExifTag("AlphaOffset"),
                [0xbcc3] = new ExifTag("AlphaByteCount"),
                [0xbcc4] = new ExifTag<ushort>("ImageDataDiscard", constants.ImageDataDiscard),
                [0xbcc5] = new ExifTag<ushort>("AlphaDataDiscard", constants.AlphaDataDiscard),
                [0xc427] = new ExifTag("OceScanjobDesc"),
                [0xc428] = new ExifTag("OceApplicationSelector"),
                [0xc429] = new ExifTag("OceIDNumber"),
                [0xc42a] = new ExifTag("OceImageLogic"),
                [0xc44f] = new ExifTag("Annotations"),
                [0xc4a5] = new ExifTag("PrintIM"),
                [0xc519] = new ExifTag("HasselbladXML"),
                [0xc51b] = new ExifTag("HasselbladExif"),
                [0xc573] = new ExifTag("OriginalFileName"),
                [0xc580] = new ExifTag<ushort>("USPTOOriginalContentType", constants.USPTOOriginalContentType),
                [0xc5e0] = new ExifTag<ushort>("CR2CFAPattern", constants.CR2CFAPattern),
                [0xc612] = new ExifTag("DNGVersion"),
                [0xc613] = new ExifTag("DNGBackwardVersion"),
                [0xc614] = new ExifTag("UniqueCameraModel"),
                [0xc615] = new ExifTag("LocalizedCameraModel"),
                [0xc616] = new ExifTag("CFAPlaneColor"),
                [0xc617] = new ExifTag<ushort>("CFALayout", constants.CFALayout),
                [0xc618] = new ExifTag("LinearizationTable"),
                [0xc619] = new ExifTag("BlackLevelRepeatDim"),
                [0xc61a] = new ExifTag("BlackLevel"),
                [0xc61b] = new ExifTag("BlackLevelDeltaH"),
                [0xc61c] = new ExifTag("BlackLevelDeltaV"),
                [0xc61d] = new ExifTag("WhiteLevel"),
                [0xc61e] = new ExifTag("DefaultScale"),
                [0xc61f] = new ExifTag("DefaultCropOrigin"),
                [0xc620] = new ExifTag("DefaultCropSize"),
                [0xc621] = new ExifTag("ColorMatrix1"),
                [0xc622] = new ExifTag("ColorMatrix2"),
                [0xc623] = new ExifTag("CameraCalibration1"),
                [0xc624] = new ExifTag("CameraCalibration2"),
                [0xc625] = new ExifTag("ReductionMatrix1"),
                [0xc626] = new ExifTag("ReductionMatrix2"),
                [0xc627] = new ExifTag("AnalogBalance"),
                [0xc628] = new ExifTag("AsShotNeutral"),
                [0xc629] = new ExifTag("AsShotWhiteXY"),
                [0xc62a] = new ExifTag("BaselineExposure"),
                [0xc62b] = new ExifTag("BaselineNoise"),
                [0xc62c] = new ExifTag("BaselineSharpness"),
                [0xc62d] = new ExifTag("BayerGreenSplit"),
                [0xc62e] = new ExifTag("LinearResponseLimit"),
                [0xc62f] = new ExifTag("CameraSerialNumber"),
                [0xc630] = new ExifTag("DNGLensInfo"),
                [0xc631] = new ExifTag("ChromaBlurRadius"),
                [0xc632] = new ExifTag("AntiAliasStrength"),
                [0xc633] = new ExifTag("ShadowScale"),
                [0xc634] = new ExifTag("SR2Private"),
                [0xc635] = new ExifTag("MakerNoteSafety"),
                [0xc640] = new ExifTag("RawImageSegmentation"),
                [0xc65a] = new ExifTag("CalibrationIlluminant1"),
                [0xc65b] = new ExifTag("CalibrationIlluminant2"),
                [0xc65c] = new ExifTag("BestQualityScale"),
                [0xc65d] = new ExifTag("RawDataUniqueID"),
                [0xc660] = new ExifTag("AliasLayerMetadata"),
                [0xc68b] = new ExifTag("OriginalRawFileName"),
                [0xc68c] = new ExifTag("OriginalRawFileData"),
                [0xc68d] = new ExifTag("ActiveArea"),
                [0xc68e] = new ExifTag("MaskedAreas"),
                [0xc68f] = new ExifTag("AsShotICCProfile"),
                [0xc690] = new ExifTag("AsShotPreProfileMatrix"),
                [0xc691] = new ExifTag("CurrentICCProfile"),
                [0xc692] = new ExifTag("CurrentPreProfileMatrix"),
                [0xc6bf] = new ExifTag<ushort>("ColorimetricReference", constants.ColorimetricReference),
                [0xc6c5] = new ExifTag("SRawType"),
                [0xc6d2] = new ExifTag("PanasonicTitle"),
                [0xc6d3] = new ExifTag("PanasonicTitle2"),
                [0xc6f3] = new ExifTag("CameraCalibrationSig"),
                [0xc6f4] = new ExifTag("ProfileCalibrationSig"),
                [0xc6f5] = new ExifTag("ProfileIFD"),
                [0xc6f6] = new ExifTag("AsShotProfileName"),
                [0xc6f7] = new ExifTag("NoiseReductionApplied"),
                [0xc6f8] = new ExifTag("ProfileName"),
                [0xc6f9] = new ExifTag("ProfileHueSatMapDims"),
                [0xc6fa] = new ExifTag("ProfileHueSatMapData1"),
                [0xc6fb] = new ExifTag("ProfileHueSatMapData2"),
                [0xc6fc] = new ExifTag("ProfileToneCurve"),
                [0xc6fd] = new ExifTag("ProfileEmbedPolicy"),
                [0xc6fe] = new ExifTag("ProfileCopyright"),
                [0xc714] = new ExifTag("ForwardMatrix1"),
                [0xc715] = new ExifTag("ForwardMatrix2"),
                [0xc716] = new ExifTag("PreviewApplicationName"),
                [0xc717] = new ExifTag("PreviewApplicationVersion"),
                [0xc718] = new ExifTag("PreviewSettingsName"),
                [0xc719] = new ExifTag("PreviewSettingsDigest"),
                [0xc71a] = new ExifTag("PreviewColorSpace"),
                [0xc71b] = new ExifTag("PreviewDateTime"),
                [0xc71c] = new ExifTag("RawImageDigest"),
                [0xc71d] = new ExifTag("OriginalRawFileDigest"),
                [0xc71e] = new ExifTag("SubTileBlockSize"),
                [0xc71f] = new ExifTag("RowInterleaveFactor"),
                [0xc725] = new ExifTag("ProfileLookTableDims"),
                [0xc726] = new ExifTag("ProfileLookTableData"),
                [0xc740] = new ExifTag("OpcodeList1"),
                [0xc741] = new ExifTag("OpcodeList2"),
                [0xc74e] = new ExifTag("OpcodeList3"),
                [0xc761] = new ExifTag("NoiseProfile"),
                [0xc763] = new ExifTag("TimeCodes"),
                [0xc764] = new ExifTag("FrameRate"),
                [0xc772] = new ExifTag("TStop"),
                [0xc789] = new ExifTag("ReelName"),
                [0xc791] = new ExifTag("OriginalDefaultFinalSize"),
                [0xc792] = new ExifTag("OriginalBestQualitySize"),
                [0xc793] = new ExifTag("OriginalDefaultCropSize"),
                [0xc7a1] = new ExifTag("CameraLabel"),
                [0xc7a3] = new ExifTag("ProfileHueSatMapEncoding"),
                [0xc7a4] = new ExifTag("ProfileLookTableEncoding"),
                [0xc7a5] = new ExifTag("BaselineExposureOffset"),
                [0xc7a6] = new ExifTag("DefaultBlackRender"),
                [0xc7a7] = new ExifTag("NewRawImageDigest"),
                [0xc7a8] = new ExifTag("RawToPreviewGain"),
                [0xc7aa] = new ExifTag("CacheVersion"),
                [0xc7b5] = new ExifTag("DefaultUserCrop"),
                [0xc7d5] = new ExifTag("NikonNEFInfo"),
                [0xc7e9] = new ExifTag("DepthFormat"),
                [0xc7ea] = new ExifTag("DepthNear"),
                [0xc7eb] = new ExifTag("DepthFar"),
                [0xc7ec] = new ExifTag("DepthUnits"),
                [0xc7ed] = new ExifTag("DepthMeasureType"),
                [0xc7ee] = new ExifTag("EnhanceParams"),
                [0xcd2d] = new ExifTag("ProfileGainTableMap"),
                [0xcd2e] = new ExifTag("SemanticName"),
                [0xcd30] = new ExifTag("SemanticInstanceID"),
                [0xcd31] = new ExifTag("CalibrationIlluminant3"),
                [0xcd32] = new ExifTag("CameraCalibration3"),
                [0xcd33] = new ExifTag("ColorMatrix3"),
                [0xcd34] = new ExifTag("ForwardMatrix3"),
                [0xcd35] = new ExifTag("IlluminantData1"),
                [0xcd36] = new ExifTag("IlluminantData2"),
                [0xcd37] = new ExifTag("IlluminantData3"),
                [0xcd38] = new ExifTag("MaskSubArea"),
                [0xcd39] = new ExifTag("ProfileHueSatMapData3"),
                [0xcd3a] = new ExifTag("ReductionMatrix3"),
                [0xcd3f] = new ExifTag("RGBTables"),
                [0xcd40] = new ExifTag("ProfileGainTableMap2"),
                [0xcd41] = new ExifTag("JUMBF"),
                [0xcd43] = new ExifTag("ColumnInterleaveFactor"),
                [0xcd44] = new ExifTag("ImageSequenceInfo"),
                [0xcd46] = new ExifTag("ImageStats"),
                [0xcd47] = new ExifTag("ProfileDynamicRange"),
                [0xcd48] = new ExifTag("ProfileGroupName"),
                [0xcd49] = new ExifTag("JXLDistance"),
                [0xcd4a] = new ExifTag("JXLEffort"),
                [0xcd4b] = new ExifTag("JXLDecodeSpeed"),
                [0xcea1] = new ExifTag("SEAL"),
                [0xea1c] = new ExifTag("Padding"),
                [0xea1d] = new ExifTag("OffsetSchema"),
                [0xfde8] = new ExifTag("OwnerName"),
                [0xfde9] = new ExifTag("Số seri"),
                [0xfdea] = new ExifTag("Lens"),
                [0xfe00] = new ExifTag("KDC_IFD"),
                [0xfe4c] = new ExifTag("RawFile"),
                [0xfe4d] = new ExifTag("Converter"),
                [0xfe4e] = new ExifTag("Cân bằng trắng"),
                [0xfe51] = new ExifTag("Exposure"),
                [0xfe52] = new ExifTag("Shadows"),
                [0xfe53] = new ExifTag("Độ sáng"),
                [0xfe54] = new ExifTag("Độ tương phản"),
                [0xfe55] = new ExifTag("Độ bão hoà"),
                [0xfe56] = new ExifTag("Độ nét"),
                [0xfe57] = new ExifTag("Độ mịn"),
                [0xfe58] = new ExifTag("MoireFilter")
            };
        }

        /// <summary>
        /// Returns the property item name from the supplied <see cref="ExifTag"/>.
        /// </summary>
        public string GetName(PropertyItem item)
        {
            return PropertyItemsDict.ContainsKey(item.Id)
                ? PropertyItemsDict[item.Id].Name
                : $"Property [0x{item.Id:X4}]";
        }

        /// <summary>
        /// Returns whether the property item id exists in the dictionary.
        /// </summary>
        public bool Contains(PropertyItem item)
        {
            return PropertyItemsDict.ContainsKey(item.Id);
        }

        /// <summary>
        /// Converts <see cref="PropertyItem"/> to <see cref="string"/> for displaying.
        /// </summary>
        public string GetValue(PropertyItem item)
        {
            try
            {
                ExifTag converter = PropertyItemsDict.ContainsKey(item.Id)
                    ? PropertyItemsDict[item.Id]
                    : new ExifTag(GetName(item));
                switch ((PropertyItemType)item.Type)
                {
                    case PropertyItemType.Byte:
                        byte[] byteArr = item.Value;
                        return converter.Convert(byteArr);
                    case PropertyItemType.Char:
                        string str = new string(item.Value.Select(v => (char)v).Take(item.Value.Length - 1).ToArray());
                        return converter.Convert(new string[] { str });
                    case PropertyItemType.UInt16:
                        ushort[] ushortArr = RawDataArrayConverter.ToUint16Array(item.Value);
                        return converter.Convert(ushortArr);
                    case PropertyItemType.UInt32:
                        uint[] uintArr = RawDataArrayConverter.ToUint32Array(item.Value);
                        return converter.Convert(uintArr);
                    case PropertyItemType.Rational:
                        Rational[] rationalArr = RawDataArrayConverter.ToRationalArray(item.Value);
                        return converter.Convert(rationalArr);
                    case PropertyItemType.Any:
                        byte[] anyArr = item.Value;
                        return converter.Convert(anyArr);
                    case PropertyItemType.Int32:
                        int[] intArr = RawDataArrayConverter.ToInt32Array(item.Value);
                        return converter.Convert(intArr);
                    case PropertyItemType.SRational:
                        SRational[] sRationalArr = RawDataArrayConverter.ToSRationalArray(item.Value);
                        return converter.Convert(sRationalArr);
                    default:
                        return "<Unknown>";
                }
            }
            catch (Exception exc)
            {
                System.Console.WriteLine("Conversion error at property " + GetName(item));
                System.Console.WriteLine(exc);
                return null;
            }
        }
    }
}
