//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaiVietRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaiVietRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyCLB.Properties.BaiVietRes", typeof(BaiVietRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy bài viết.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachBaiViet_Loi_1 {
            get {
                return ResourceManager.GetString("DanhSachBaiViet_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện chưa có bài viết nào..
        /// </summary>
        internal static string DanhSachBaiViet_Trong {
            get {
                return ResourceManager.GetString("DanhSachBaiViet_Trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_properties_2_16 {
            get {
                object obj = ResourceManager.GetObject("document_properties_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_5_16 {
            get {
                object obj = ResourceManager.GetObject("document_save_5_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy_7 {
            get {
                object obj = ResourceManager.GetObject("edit_copy_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_cut_5 {
            get {
                object obj = ResourceManager.GetObject("edit_cut_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_paste_4 {
            get {
                object obj = ResourceManager.GetObject("edit_paste_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_redo_8 {
            get {
                object obj = ResourceManager.GetObject("edit_redo_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_undo_8 {
            get {
                object obj = ResourceManager.GetObject("edit_undo_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font {
            get {
                object obj = ResourceManager.GetObject("font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_list_ordered {
            get {
                object obj = ResourceManager.GetObject("format_list_ordered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_list_unordered {
            get {
                object obj = ResourceManager.GetObject("format_list_unordered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_align_center {
            get {
                object obj = ResourceManager.GetObject("format_text_align_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_align_justify {
            get {
                object obj = ResourceManager.GetObject("format_text_align_justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_align_left {
            get {
                object obj = ResourceManager.GetObject("format_text_align_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_align_right {
            get {
                object obj = ResourceManager.GetObject("format_text_align_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_allcaps {
            get {
                object obj = ResourceManager.GetObject("format_text_allcaps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_bold_5 {
            get {
                object obj = ResourceManager.GetObject("format_text_bold_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_smallcaps {
            get {
                object obj = ResourceManager.GetObject("format_text_smallcaps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_strikethrough_4 {
            get {
                object obj = ResourceManager.GetObject("format_text_strikethrough_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_subscript_3 {
            get {
                object obj = ResourceManager.GetObject("format_text_subscript_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_superscript_3 {
            get {
                object obj = ResourceManager.GetObject("format_text_superscript_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap format_text_underline_5 {
            get {
                object obj = ResourceManager.GetObject("format_text_underline_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_x_generic_16 {
            get {
                object obj = ResourceManager.GetObject("image_x_generic_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_horizontal_rule {
            get {
                object obj = ResourceManager.GetObject("insert_horizontal_rule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_table_2 {
            get {
                object obj = ResourceManager.GetObject("insert_table_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_text_italic {
            get {
                object obj = ResourceManager.GetObject("insert_text_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kdb_table1 {
            get {
                object obj = ResourceManager.GetObject("kdb_table1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap script1 {
            get {
                object obj = ResourceManager.GetObject("script1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn đóng trình soạn thảo và lưu bài viết này không?.
        /// </summary>
        internal static string SoanBaiViet_ChuaLuu_NoiDung {
            get {
                return ResourceManager.GetString("SoanBaiViet_ChuaLuu_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết chưa lưu.
        /// </summary>
        internal static string SoanBaiViet_ChuaLuu_TieuDe {
            get {
                return ResourceManager.GetString("SoanBaiViet_ChuaLuu_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết &apos;{0}&apos; đã được gửi thành công lên câu lạc bộ &apos;{1}&apos;..
        /// </summary>
        internal static string SoanBaiViet_Gui_HoanThanh_NoiDung_2 {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_HoanThanh_NoiDung_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi bài viết..
        /// </summary>
        internal static string SoanBaiViet_Gui_HoanThanh_TieuDe {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_HoanThanh_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể gửi bài viết.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string SoanBaiViet_Gui_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi gửi bài viết.
        /// </summary>
        internal static string SoanBaiViet_Gui_Loi_TieuDe {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn tải bài viết này lên trang câu lạc bộ &apos;{0}&apos; không?.
        /// </summary>
        internal static string SoanBaiViet_Gui_XacNhan_NoiDung_1 {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_XacNhan_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên.
        /// </summary>
        internal static string SoanBaiViet_Gui_XacNhanGui_TieuDe {
            get {
                return ResourceManager.GetString("SoanBaiViet_Gui_XacNhanGui_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_split_left_right_2_16 {
            get {
                object obj = ResourceManager.GetObject("view_split_left_right_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_split_top_bottom_2_16 {
            get {
                object obj = ResourceManager.GetObject("view_split_top_bottom_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bởi {0}, ngày {1}.
        /// </summary>
        internal static string XemBaiViet_Boi_2 {
            get {
                return ResourceManager.GetString("XemBaiViet_Boi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể mở bài viết này.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string XemBaiViet_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("XemBaiViet_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xem bài viết.
        /// </summary>
        internal static string XemBaiViet_Loi_TieuDe {
            get {
                return ResourceManager.GetString("XemBaiViet_Loi_TieuDe", resourceCulture);
            }
        }
    }
}
