//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuuTruRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuuTruRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyCLB.Properties.LuuTruRes", typeof(LuuTruRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_high {
            get {
                object obj = ResourceManager.GetObject("audio_volume_high", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_low {
            get {
                object obj = ResourceManager.GetObject("audio_volume_low", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_medium {
            get {
                object obj = ResourceManager.GetObject("audio_volume_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_volume_muted {
            get {
                object obj = ResourceManager.GetObject("audio_volume_muted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần duyệt..
        /// </summary>
        internal static string DanhSachTapTin_Chon0 {
            get {
                return ResourceManager.GetString("DanhSachTapTin_Chon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần di chuyển các tập tin đến đó.
        ///Nhấn nút Esc để huỷ thao tác..
        /// </summary>
        internal static string DanhSachTapTin_DiChuyen_ChuanBi {
            get {
                return ResourceManager.GetString("DanhSachTapTin_DiChuyen_ChuanBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc duyệt các tập tin.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachTapTin_Duyet_Loi_1 {
            get {
                return ResourceManager.GetString("DanhSachTapTin_Duyet_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần sao chép các tập tin đến đó.
        ///Nhấn nút Esc để huỷ thao tác..
        /// </summary>
        internal static string DanhSachTapTin_SaoChep_ChuanBi {
            get {
                return ResourceManager.GetString("DanhSachTapTin_SaoChep_ChuanBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thả vào đây để tải tập tin lên..
        /// </summary>
        internal static string DanhSachTapTin_ThaDeTaiLen {
            get {
                return ResourceManager.GetString("DanhSachTapTin_ThaDeTaiLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục trống..
        /// </summary>
        internal static string DanhSachTapTin_Trong {
            get {
                return ResourceManager.GetString("DanhSachTapTin_Trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc duyệt các thư mục.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachThuMuc_Duyet_Loi_1 {
            get {
                return ResourceManager.GetString("DanhSachThuMuc_Duyet_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_641 {
            get {
                object obj = ResourceManager.GetObject("folder_641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_forbidden {
            get {
                object obj = ResourceManager.GetObject("folder_forbidden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_forbidden_16 {
            get {
                object obj = ResourceManager.GetObject("folder_forbidden_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_new_5 {
            get {
                object obj = ResourceManager.GetObject("folder_new_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_new_5_16 {
            get {
                object obj = ResourceManager.GetObject("folder_new_5_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_3 {
            get {
                object obj = ResourceManager.GetObject("folder_open_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder1 {
            get {
                object obj = ResourceManager.GetObject("folder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải về.
        /// </summary>
        internal static string GiaoDienTrinhDoc_TaiVe_Loi_TieuDe {
            get {
                return ResourceManager.GetString("GiaoDienTrinhDoc_TaiVe_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("pause_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_arrow_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("play_arrow_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skip_next_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("skip_next_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skip_previous_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("skip_previous_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speed_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("speed_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_16dp_5f6368_fill1_wght400_grad0_opsz201 {
            get {
                object obj = ResourceManager.GetObject("stop_16dp_5f6368_fill1_wght400_grad0_opsz201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã di chuyển {0}/{1} file vào thư mục &apos;{2}&apos;..
        /// </summary>
        internal static string TapTin_DiChuyen_HoanThanh_3 {
            get {
                return ResourceManager.GetString("TapTin_DiChuyen_HoanThanh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tập tin cần di chuyển trước tiên..
        /// </summary>
        internal static string TapTin_DiChuyen_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_DiChuyen_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể di chuyển các tập tin vào cùng thư mục..
        /// </summary>
        internal static string TapTin_DiChuyen_LoiCungThuMuc {
            get {
                return ResourceManager.GetString("TapTin_DiChuyen_LoiCungThuMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đổi tên tập tin &apos;{0}&apos; thành &apos;{1}&apos;..
        /// </summary>
        internal static string TapTin_DoiTen_HoanThanh_2 {
            get {
                return ResourceManager.GetString("TapTin_DoiTen_HoanThanh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi tên tập tin.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string TapTin_DoiTen_Loi_1 {
            get {
                return ResourceManager.GetString("TapTin_DoiTen_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần chọn tập tin trước khi đổi tên..
        /// </summary>
        internal static string TapTin_DoiTen_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_DoiTen_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ chọn 1 tập tin để đổi tên..
        /// </summary>
        internal static string TapTin_DoiTen_LoiChonNhieu {
            get {
                return ResourceManager.GetString("TapTin_DoiTen_LoiChonNhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đặt tên không chứa các ký hiệu sau:
        ///\  /  :  *  ?  &quot;  &lt;  &gt;  |.
        /// </summary>
        internal static string TapTin_DoiTen_LoiTenChuaKyHieu {
            get {
                return ResourceManager.GetString("TapTin_DoiTen_LoiTenChuaKyHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tập tin cần mở..
        /// </summary>
        internal static string TapTin_Mo_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_Mo_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ chọn 1 tập tin để xem trước..
        /// </summary>
        internal static string TapTin_Mo_LoiChonNhieu_NoiDung {
            get {
                return ResourceManager.GetString("TapTin_Mo_LoiChonNhieu_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tìm thấy tập tin cần mở..
        /// </summary>
        internal static string TapTin_Mo_LoiKhongTimThay {
            get {
                return ResourceManager.GetString("TapTin_Mo_LoiKhongTimThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sao chép {0}/{1} tập tin vào thư mục &apos;{2}&apos;..
        /// </summary>
        internal static string TapTin_SaoChep_HoanThanh_3 {
            get {
                return ResourceManager.GetString("TapTin_SaoChep_HoanThanh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tập tin cần sao chép trước tiên..
        /// </summary>
        internal static string TapTin_SaoChep_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_SaoChep_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải lên.
        /// </summary>
        internal static string TapTin_TaiLen_DangTaiLen {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_DangTaiLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tải lên xong..
        /// </summary>
        internal static string TapTin_TaiLen_HoanThanh {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã huỷ tải file lên..
        /// </summary>
        internal static string TapTin_TaiLen_Huy_NoiDung {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_Huy_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ tải lên.
        /// </summary>
        internal static string TapTin_TaiLen_Huy_TieuDe {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_Huy_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc tải tập tin lên.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string TapTin_TaiLen_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải lên.
        /// </summary>
        internal static string TapTin_TaiLen_Loi_TieuDe {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kéo thả 1 hoặc nhiều tập tin vào để tải lên..
        /// </summary>
        internal static string TapTin_TaiLen_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần tải lên trước tiên..
        /// </summary>
        internal static string TapTin_TaiLen_LoiKhongChonThuMuc {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_LoiKhongChonThuMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại..
        /// </summary>
        internal static string TapTin_TaiLen_LoiKhongTimThay {
            get {
                return ResourceManager.GetString("TapTin_TaiLen_LoiKhongTimThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangCho {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangCho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải lên.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangTaiLen {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangTaiLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải về.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangTaiVe {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_DangTaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_HoanThanh {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã huỷ.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_Huy {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_Huy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: {0}.
        /// </summary>
        internal static string TapTin_TaiLenTaiXuongNhieu_TinhTrang_Loi_1 {
            get {
                return ResourceManager.GetString("TapTin_TaiLenTaiXuongNhieu_TinhTrang_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải về.
        /// </summary>
        internal static string TapTin_TaiVe_DangTaiVe {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_DangTaiVe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tải về xong..
        /// </summary>
        internal static string TapTin_TaiVe_HoanThanh {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã huỷ tải tập tin về.
        /// </summary>
        internal static string TapTin_TaiVe_Huy_NoiDung {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_Huy_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ tải về.
        /// </summary>
        internal static string TapTin_TaiVe_Huy_TieuDe {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_Huy_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc tải tập tin về.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string TapTin_TaiVe_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải về.
        /// </summary>
        internal static string TapTin_TaiVe_Loi_TieuDe {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tập tin cần tải về trước tiên..
        /// </summary>
        internal static string TapTin_TaiVe_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại..
        /// </summary>
        internal static string TapTin_TaiVe_LoiKhongTimThay {
            get {
                return ResourceManager.GetString("TapTin_TaiVe_LoiKhongTimThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xoá {0}/{1} tập tin..
        /// </summary>
        internal static string TapTin_Xoa_HoanThanh_2 {
            get {
                return ResourceManager.GetString("TapTin_Xoa_HoanThanh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tập tin cần xoá trước tiên..
        /// </summary>
        internal static string TapTin_Xoa_LoiChon0 {
            get {
                return ResourceManager.GetString("TapTin_Xoa_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá tập tin.
        /// </summary>
        internal static string TapTin_Xoa_XacNhan_TieuDe {
            get {
                return ResourceManager.GetString("TapTin_Xoa_XacNhan_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xoá tập tin &apos;{0}&apos; không?
        ///Bạn sẽ không thể khôi phục sau khi xoá!.
        /// </summary>
        internal static string TapTin_Xoa_XacNhanMot_NoiDung_1 {
            get {
                return ResourceManager.GetString("TapTin_Xoa_XacNhanMot_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xoá {0} tập tin đã chọn không?
        ///Bạn sẽ không thể khôi phục sau khi xoá!.
        /// </summary>
        internal static string TapTin_Xoa_XacNhanNhieu_NoiDung_1 {
            get {
                return ResourceManager.GetString("TapTin_Xoa_XacNhanNhieu_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thư mục.
        /// </summary>
        internal static string ThuMuc_Sua_TieuDe {
            get {
                return ResourceManager.GetString("ThuMuc_Sua_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thư mục thành công..
        /// </summary>
        internal static string ThuMuc_SuaDoi_HoanThanh {
            get {
                return ResourceManager.GetString("ThuMuc_SuaDoi_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thư mục.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string ThuMuc_SuaDoi_Loi_1 {
            get {
                return ResourceManager.GetString("ThuMuc_SuaDoi_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần sửa đổi trước tiên..
        /// </summary>
        internal static string ThuMuc_SuaDoi_LoiChon0 {
            get {
                return ResourceManager.GetString("ThuMuc_SuaDoi_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thư mục thành công..
        /// </summary>
        internal static string ThuMuc_Them_HoanThanh {
            get {
                return ResourceManager.GetString("ThuMuc_Them_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo thư mục.
        ///Mô tả lỗi: {0}.
        /// </summary>
        internal static string ThuMuc_Them_Loi_1 {
            get {
                return ResourceManager.GetString("ThuMuc_Them_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục mới.
        /// </summary>
        internal static string ThuMuc_Them_ThuMucMoi {
            get {
                return ResourceManager.GetString("ThuMuc_Them_ThuMucMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thư mục.
        /// </summary>
        internal static string ThuMuc_Them_TieuDe {
            get {
                return ResourceManager.GetString("ThuMuc_Them_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền tên thư mục..
        /// </summary>
        internal static string ThuMuc_ThemSua_LoiKhongTen {
            get {
                return ResourceManager.GetString("ThuMuc_ThemSua_LoiKhongTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đặt tên không chứa các ký hiệu sau:
        ///\  /  :  *  ?  &quot;  &lt;  &gt;  |.
        /// </summary>
        internal static string ThuMuc_ThemSua_LoiTenChuaKyHieu {
            get {
                return ResourceManager.GetString("ThuMuc_ThemSua_LoiTenChuaKyHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xoá thư mục &apos;{0}&apos;..
        /// </summary>
        internal static string ThuMuc_Xoa_HoanThanh_1 {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_HoanThanh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá thư mục.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string ThuMuc_Xoa_Loi_1 {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thư mục cần xoá trước tiên..
        /// </summary>
        internal static string ThuMuc_Xoa_LoiChon0 {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_LoiChon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tìm thấy thư mục cần xoá..
        /// </summary>
        internal static string ThuMuc_Xoa_LoiKhongTimThay {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_LoiKhongTimThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục &apos;{0}&apos; là thư mục gốc và không thể xoá..
        /// </summary>
        internal static string ThuMuc_Xoa_LoiThuMucGoc_1 {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_LoiThuMucGoc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xoá thư mục này?.
        /// </summary>
        internal static string ThuMuc_Xoa_XacNhan_NoiDung {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_XacNhan_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thư mục.
        /// </summary>
        internal static string ThuMuc_Xoa_XacNhan_TieuDe {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_XacNhan_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục này có chứa tập tin.
        ///Bạn có chắc muốn xoá thư mục này và di chuyển tất cả các tập tin về thư mục gốc ({0})?.
        /// </summary>
        internal static string ThuMuc_Xoa_XacNhanKhongTrong_NoiDung_1 {
            get {
                return ResourceManager.GetString("ThuMuc_Xoa_XacNhanKhongTrong_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại..
        /// </summary>
        internal static string TrinhDoc_Loi_KhongTonTai_NoiDung {
            get {
                return ResourceManager.GetString("TrinhDoc_Loi_KhongTonTai_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại.
        /// </summary>
        internal static string TrinhDoc_Loi_KhongTonTai_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDoc_Loi_KhongTonTai_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy tập tin.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string TrinhDoc_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("TrinhDoc_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải tập tin.
        /// </summary>
        internal static string TrinhDoc_Loi_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDoc_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng pixel.
        /// </summary>
        internal static string TrinhDocHinhAnh_DinhDangPixel_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDocHinhAnh_DinhDangPixel_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        internal static string TrinhDocHinhAnh_KichThuoc_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDocHinhAnh_KichThuoc_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string TrinhDocHinhAnh_KinhThuoc_NoiDung_2 {
            get {
                return ResourceManager.GetString("TrinhDocHinhAnh_KinhThuoc_NoiDung_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string TrinhDocHinhAnh_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDocHinhAnh_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các diễn viên.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Actors {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Album {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả album.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_AlbumArtist {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_AlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Artist {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình album.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_ArtworkURL {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_ArtworkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Copyright {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Date {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Description {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đạo diễn.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Director {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đĩa.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_DiscNumber {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_DiscNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số đĩa.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_DiscTotal {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_DiscTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hoá bằng.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_EncodedBy {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_EncodedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Episode {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể loại nhạc.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Genre {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Language {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện đang phát.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_NowPlaying {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà xuất bản.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Publisher {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Rating {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mùa.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Season {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuỳ chỉnh.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Setting {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chương trình.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_ShowName {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_ShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_Title {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhạc.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_TrackID {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_TrackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhạc.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_TrackNumber {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_TrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số nhạc.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_TrackTotal {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_TrackTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ web.
        /// </summary>
        internal static string TrinhDocVideo_Metadata_URL {
            get {
                return ResourceManager.GetString("TrinhDocVideo_Metadata_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng.
        /// </summary>
        internal static string TrinhDocVideo_ThoiLuong_TieuDe {
            get {
                return ResourceManager.GetString("TrinhDocVideo_ThoiLuong_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Âm thanh.
        /// </summary>
        internal static string TrinhDocVideo_TieuDe_Audio {
            get {
                return ResourceManager.GetString("TrinhDocVideo_TieuDe_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string TrinhDocVideo_TieuDe_Video {
            get {
                return ResourceManager.GetString("TrinhDocVideo_TieuDe_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_list_details_4 {
            get {
                object obj = ResourceManager.GetObject("view_list_details_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_list_icons {
            get {
                object obj = ResourceManager.GetObject("view_list_icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
