//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCLB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyCLB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _312206908_556418156487551_722616506666904791_n__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_312206908_556418156487551_722616506666904791_n__1__removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _737963dd93d62b8872c7 {
            get {
                object obj = ResourceManager.GetObject("_737963dd93d62b8872c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accessories_text_editor_8 {
            get {
                object obj = ResourceManager.GetObject("accessories_text_editor_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_3 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_3 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio_x_generic_2 {
            get {
                object obj = ResourceManager.GetObject("audio_x_generic_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner_v3 {
            get {
                object obj = ResourceManager.GetObject("banner_v3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy thông tin thành viên.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string CauLacBo_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("CauLacBo_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải thành viên.
        /// </summary>
        internal static string CauLacBo_Loi_TieuDe {
            get {
                return ResourceManager.GetString("CauLacBo_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chromium_2 {
            get {
                object obj = ResourceManager.GetObject("chromium_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_picker {
            get {
                object obj = ResourceManager.GetObject("color_picker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình đăng ký.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DangKy_Loi_NoiDung {
            get {
                return ResourceManager.GetString("DangKy_Loi_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đăng ký.
        /// </summary>
        internal static string DangKy_Loi_TieuDe {
            get {
                return ResourceManager.GetString("DangKy_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng ký tài khoản thành công!
        ///Hiện tại đội ngũ của chúng tôi đang tiến hành duyệt tài khoản của bạn, xin vui lòng chờ một khoảng thời gian trước khi đăng nhập bằng tài khoản của bạn..
        /// </summary>
        internal static string DangKy_ThanhCong_NoiDung {
            get {
                return ResourceManager.GetString("DangKy_ThanhCong_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công.
        /// </summary>
        internal static string DangKy_ThanhCong_TieuDe {
            get {
                return ResourceManager.GetString("DangKy_ThanhCong_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc đăng nhập.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DangNhap_Loi_1 {
            get {
                return ResourceManager.GetString("DangNhap_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện chưa được duyệt. Vui lòng chờ thêm một khoảng thời gian..
        /// </summary>
        internal static string DangNhap_TaiKhoanChuaDuyet_NoiDung {
            get {
                return ResourceManager.GetString("DangNhap_TaiKhoanChuaDuyet_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được duyệt..
        /// </summary>
        internal static string DangNhap_TaiKhoanChuaDuyet_TieuDe {
            get {
                return ResourceManager.GetString("DangNhap_TaiKhoanChuaDuyet_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi rất tiếc rằng tài khoản của bạn đã không được chấp nhận duyệt.
        ///Nguyên nhân là do các thông tin mà bạn cung cấp không phù hợp với yêu cầu và tiêu chuẩn của chúng tôi..
        /// </summary>
        internal static string DangNhap_TaiKhoanTuChoi_NoiDung {
            get {
                return ResourceManager.GetString("DangNhap_TaiKhoanTuChoi_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị từ chối duyệt..
        /// </summary>
        internal static string DangNhap_TaiKhoanTuChoi_TieuDe {
            get {
                return ResourceManager.GetString("DangNhap_TaiKhoanTuChoi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy thông tin câu lạc bộ.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachCauLacBo_Loi_1 {
            get {
                return ResourceManager.GetString("DanhSachCauLacBo_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm người dùng bằng họ, tên hoặc mã số sinh viên và nhấn đúp để thêm người dùng.
        ///Nhấn Esc để huỷ..
        /// </summary>
        internal static string DanhSachThanhVien_ChuanBiThem_NoiDung {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_ChuanBiThem_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc đổi chức vụ.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachThanhVien_DoiChucVu_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_DoiChucVu_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đổi chức vụ.
        /// </summary>
        internal static string DanhSachThanhVien_DoiChucVu_Loi_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_DoiChucVu_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi chức vụ khi đang trong chế độ thêm thành viên.
        ///Nhấn Esc để thoát khỏi chế độ này..
        /// </summary>
        internal static string DanhSachThanhVien_DoiChucVu_LoiCheDoThem {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_DoiChucVu_LoiCheDoThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_SoLuongThanhVien {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_SoLuongThanhVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc thêm thành viên.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachThanhVien_Them_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Them_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_Them_Loi_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Them_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm người dùng &apos;{0}&apos; vì đã là thành viên trong câu lạc bộ này..
        /// </summary>
        internal static string DanhSachThanhVien_Them_LoiTrungKhop_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Them_LoiTrungKhop_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã là thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_Them_LoiTrungKhop_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Them_LoiTrungKhop_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn đổi chức vụ của thành viên &apos;{0}&apos; thành &apos;{1}&apos; không?.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanDoiChucVu_NoiDung_2 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanDoiChucVu_NoiDung_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi chức vụ.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanDoiChucVu_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanDoiChucVu_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thêm người dùng &apos;{0}&apos; vào câu lạc bộ này không?.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanThem_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanThem_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanThem_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanThem_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xoá thành viên &apos;{0}&apos; ra khỏi câu lạc bộ này không?.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanXoa_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanXoa_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_XacNhanXoa_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_XacNhanXoa_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc xoá thành viên.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string DanhSachThanhVien_Xoa_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Xoa_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xoá thành viên.
        /// </summary>
        internal static string DanhSachThanhVien_Xoa_Loi_TieuDe {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Xoa_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá thành viên khi đang trong chế độ thêm thành viên.
        ///Nhấn Esc để thoát khỏi chế độ này..
        /// </summary>
        internal static string DanhSachThanhVien_Xoa_LoiCheDoThem {
            get {
                return ResourceManager.GetString("DanhSachThanhVien_Xoa_LoiCheDoThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_cancel_2 {
            get {
                object obj = ResourceManager.GetObject("dialog_cancel_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_cancel_2_24 {
            get {
                object obj = ResourceManager.GetObject("dialog_cancel_2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_information_3 {
            get {
                object obj = ResourceManager.GetObject("dialog_information_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_information_3_16 {
            get {
                object obj = ResourceManager.GetObject("dialog_information_3_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dialog_ok_2 {
            get {
                object obj = ResourceManager.GetObject("dialog_ok_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_properties_2 {
            get {
                object obj = ResourceManager.GetObject("document_properties_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_properties_2_16 {
            get {
                object obj = ResourceManager.GetObject("document_properties_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_2 {
            get {
                object obj = ResourceManager.GetObject("document_save_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_2_16 {
            get {
                object obj = ResourceManager.GetObject("document_save_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_save_5 {
            get {
                object obj = ResourceManager.GetObject("document_save_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap draw_arrow_back {
            get {
                object obj = ResourceManager.GetObject("draw_arrow_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy_6 {
            get {
                object obj = ResourceManager.GetObject("edit_copy_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy_6_24 {
            get {
                object obj = ResourceManager.GetObject("edit_copy_6_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy_7 {
            get {
                object obj = ResourceManager.GetObject("edit_copy_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_cut_5 {
            get {
                object obj = ResourceManager.GetObject("edit_cut_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_cut_5_24 {
            get {
                object obj = ResourceManager.GetObject("edit_cut_5_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_delete_2 {
            get {
                object obj = ResourceManager.GetObject("edit_delete_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_delete_5 {
            get {
                object obj = ResourceManager.GetObject("edit_delete_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_delete_5_16 {
            get {
                object obj = ResourceManager.GetObject("edit_delete_5_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_delete_6 {
            get {
                object obj = ResourceManager.GetObject("edit_delete_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_group {
            get {
                object obj = ResourceManager.GetObject("edit_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_remove_3 {
            get {
                object obj = ResourceManager.GetObject("edit_remove_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_rename {
            get {
                object obj = ResourceManager.GetObject("edit_rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emblem_downloads {
            get {
                object obj = ResourceManager.GetObject("emblem_downloads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon_WPS_Photos_3 {
            get {
                object obj = ResourceManager.GetObject("favicon_WPS_Photos_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_broken {
            get {
                object obj = ResourceManager.GetObject("file_broken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng tắt hết các form khác trước khi tắt giao diện này..
        /// </summary>
        internal static string GiaoDienChinh_FormDangMo_NoiDung {
            get {
                return ResourceManager.GetString("GiaoDienChinh_FormDangMo_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các form đang mở.
        /// </summary>
        internal static string GiaoDienChinh_FormDangMo_TieuDe {
            get {
                return ResourceManager.GetString("GiaoDienChinh_FormDangMo_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong giao diện chính.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string GiaoDienChinh_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("GiaoDienChinh_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi giao diện chính.
        /// </summary>
        internal static string GiaoDienChinh_Loi_TieuDe {
            get {
                return ResourceManager.GetString("GiaoDienChinh_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_down {
            get {
                object obj = ResourceManager.GetObject("go_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap go_up {
            get {
                object obj = ResourceManager.GetObject("go_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group {
            get {
                object obj = ResourceManager.GetObject("group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi thông báo lên {0}..
        /// </summary>
        internal static string GuiThongBao_HoanThanh_NoiDung_1 {
            get {
                return ResourceManager.GetString("GuiThongBao_HoanThanh_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông báo thành công.
        /// </summary>
        internal static string GuiThongBao_HoanThanh_TieuDe {
            get {
                return ResourceManager.GetString("GuiThongBao_HoanThanh_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc gửi thông báo.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string GuiThongBao_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("GuiThongBao_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi gửi thông báo.
        /// </summary>
        internal static string GuiThongBao_Loi_TieuDe {
            get {
                return ResourceManager.GetString("GuiThongBao_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_x_generic {
            get {
                object obj = ResourceManager.GetObject("image_x_generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_x_generic_16 {
            get {
                object obj = ResourceManager.GetObject("image_x_generic_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_horizontal_rule {
            get {
                object obj = ResourceManager.GetObject("insert_horizontal_rule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_table_2 {
            get {
                object obj = ResourceManager.GetObject("insert_table_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap insert_text_italic {
            get {
                object obj = ResourceManager.GetObject("insert_text_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap internet_chat_2 {
            get {
                object obj = ResourceManager.GetObject("internet_chat_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kalzium_2 {
            get {
                object obj = ResourceManager.GetObject("kalzium_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kalzium_2_24 {
            get {
                object obj = ResourceManager.GetObject("kalzium_2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kalzium_2_64 {
            get {
                object obj = ResourceManager.GetObject("kalzium_2_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_add_4 {
            get {
                object obj = ResourceManager.GetObject("list_add_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_remove_3 {
            get {
                object obj = ResourceManager.GetObject("list_remove_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_remove_5 {
            get {
                object obj = ResourceManager.GetObject("list_remove_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap message_news {
            get {
                object obj = ResourceManager.GetObject("message_news", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap multimedia_player_mp3player_alt {
            get {
                object obj = ResourceManager.GetObject("multimedia_player_mp3player_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preferences_desktop_notification_bell_2 {
            get {
                object obj = ResourceManager.GetObject("preferences_desktop_notification_bell_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật lịch nhưng không thể gửi thông báo về lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_GuiThongBao_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_GuiThongBao_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giữ chuột trái và kéo vào lịch để tạo lịch hoạt động mới..
        /// </summary>
        internal static string QuanLyLich_HuongDanKeoTha {
            get {
                return ResourceManager.GetString("QuanLyLich_HuongDanKeoTha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình lấy thông tin lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật lịch thành công..
        /// </summary>
        internal static string QuanLyLich_Sua_HoanThanh {
            get {
                return ResourceManager.GetString("QuanLyLich_Sua_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình sửa lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_Sua_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_Sua_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật lịch nhưng không thể tải lại lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_TaiLaiSauCapNhat_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_TaiLaiSauCapNhat_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm lịch thành công..
        /// </summary>
        internal static string QuanLyLich_Them_HoanThanh {
            get {
                return ResourceManager.GetString("QuanLyLich_Them_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình thêm lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_Them_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_Them_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kính gửi: Tất cả các thành viên trong câu lạc bộ {0},
        ///
        ///Tôi xin thông báo về việc sửa đổi lịch hoạt động &apos;{1}&apos; trong câu lạc bộ {0}.
        ///Cụ thể:
        ///- Chủ đề: {2}
        ///- Địa điểm: {3}
        ///- Ngày bắt đầu: {5}
        ///- Thời gian: {6} - {7}
        ///- Nội dung:
        ///{4}
        ///
        ///Hãy chú ý theo dõi để không bỏ lỡ cơ hội tham gia và trải nghiệm những hoạt động thú vị này!
        ///
        ///Xin chân thành cảm ơn..
        /// </summary>
        internal static string QuanLyLich_ThongBao_Sua_NoiDung_8 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Sua_NoiDung_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sửa đổi: {0}.
        /// </summary>
        internal static string QuanLyLich_ThongBao_Sua_TieuDe_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Sua_TieuDe_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kính gửi: Tất cả các thành viên trong câu lạc bộ {0},
        ///
        ///Tôi xin thông báo về lịch hoạt động mới vừa được thêm vào trong câu lạc bộ {0}.
        ///
        ///Cụ thể:
        ///- Chủ đề: {1}
        ///- Địa điểm: {2}
        ///- Ngày bắt đầu: {4}
        ///- Thời gian: {5} - {6}
        ///- Nội dung:
        ///{3}
        ///
        ///Hãy chú ý theo dõi để không bỏ lỡ cơ hội tham gia và trải nghiệm những hoạt động thú vị này!
        ///
        ///
        ///Xin chân thành cảm ơn..
        /// </summary>
        internal static string QuanLyLich_ThongBao_Them_NoiDung_7 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Them_NoiDung_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch mới: {0}.
        /// </summary>
        internal static string QuanLyLich_ThongBao_Them_TieuDe_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Them_TieuDe_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kính gửi: Tất cả các thành viên trong câu lạc bộ {0},
        ///
        ///Tôi xin thông báo về việc xoá lịch hoạt động &apos;{1}&apos; khỏi câu lạc bộ {0}.
        ///
        ///Hãy chú ý theo dõi để không bỏ lỡ cơ hội tham gia và trải nghiệm những hoạt động thú vị này!
        ///
        ///
        ///Xin chân thành cảm ơn..
        /// </summary>
        internal static string QuanLyLich_ThongBao_Xoa_NoiDung_2 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Xoa_NoiDung_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch đã xoá: {0}.
        /// </summary>
        internal static string QuanLyLich_ThongBao_Xoa_TieuDe_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_ThongBao_Xoa_TieuDe_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xoá lịch thành công..
        /// </summary>
        internal static string QuanLyLich_Xoa_HoanThanh {
            get {
                return ResourceManager.GetString("QuanLyLich_Xoa_HoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình xoá lịch.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string QuanLyLich_Xoa_Loi_1 {
            get {
                return ResourceManager.GetString("QuanLyLich_Xoa_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại hoặc mật khẩu không đúng..
        /// </summary>
        internal static string SignInCredentialInvalid {
            get {
                return ResourceManager.GetString("SignInCredentialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled by user..
        /// </summary>
        internal static string SqlOperationCancelled {
            get {
                return ResourceManager.GetString("SqlOperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang trong quá trình sửa lịch. Vui lòng giải quyết công việc này trước khi đăng xuất..
        /// </summary>
        internal static string SuaLich_Dong_LoiDangSua_NoiDung {
            get {
                return ResourceManager.GetString("SuaLich_Dong_LoiDangSua_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang trong quá trình sửa lịch.
        /// </summary>
        internal static string SuaLich_Dong_LoiDangSua_TieuDe {
            get {
                return ResourceManager.GetString("SuaLich_Dong_LoiDangSua_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ngày bắt đầu trước ngày kết thúc..
        /// </summary>
        internal static string SuaLich_Ngay_Hon {
            get {
                return ResourceManager.GetString("SuaLich_Ngay_Hon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thời gian bắt đầu trước thời gian kết thúc..
        /// </summary>
        internal static string SuaLich_ThoiGian_Hon {
            get {
                return ResourceManager.GetString("SuaLich_ThoiGian_Hon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian không hợp lệ..
        /// </summary>
        internal static string SuaLich_ThoiGian_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("SuaLich_ThoiGian_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xoá lịch &apos;{0}&apos; không?.
        /// </summary>
        internal static string SuaLich_XacNhanXoa_NoiDung_1 {
            get {
                return ResourceManager.GetString("SuaLich_XacNhanXoa_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá lịch.
        /// </summary>
        internal static string SuaLich_XacNhanXoa_TieuDe {
            get {
                return ResourceManager.GetString("SuaLich_XacNhanXoa_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap system_settings {
            get {
                object obj = ResourceManager.GetObject("system_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap system_users_3 {
            get {
                object obj = ResourceManager.GetObject("system_users_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap text_x_generic {
            get {
                object obj = ResourceManager.GetObject("text_x_generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ..
        /// </summary>
        internal static string TextValidator_Email_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_Email_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng ghi đúng 1 từ vào phần họ..
        /// </summary>
        internal static string TextValidator_Ho_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_Ho_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu gồm tối thiểu 10 ký tự..
        /// </summary>
        internal static string TextValidator_MatKhau_LoiDoDaiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_MatKhau_LoiDoDaiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải chứa cả chữ cái, chữ số lẫn ký hiệu..
        /// </summary>
        internal static string TextValidator_MatKhau_LoiKyTuKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_MatKhau_LoiKyTuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không phù hợp..
        /// </summary>
        internal static string TextValidator_NgaySinh_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_NgaySinh_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ..
        /// </summary>
        internal static string TextValidator_SDT_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_SDT_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng ghi đúng 1 từ vào phần tên. Nếu họ tên có 3 từ trở lên thì ghi các từ giữa vào tên lót..
        /// </summary>
        internal static string TextValidator_Ten_LoiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_Ten_LoiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập gồm tối thiểu 6 ký tự..
        /// </summary>
        internal static string TextValidator_TenDangNhap_LoiDoDaiKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_TenDangNhap_LoiDoDaiKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được bắt đầu bằng số..
        /// </summary>
        internal static string TextValidator_TenDangNhap_LoiKyTuDauKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_TenDangNhap_LoiKyTuDauKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập chỉ được chứa chữ cái không dấu, chữ số và dấu gạch dưới (_)..
        /// </summary>
        internal static string TextValidator_TenDangNhap_LoiKyTuKhongHopLe {
            get {
                return ResourceManager.GetString("TextValidator_TenDangNhap_LoiKyTuKhongHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền tất cả thông tin..
        /// </summary>
        internal static string TextValidator_Trong {
            get {
                return ResourceManager.GetString("TextValidator_Trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không trùng khớp..
        /// </summary>
        internal static string TextValidator_XacNhanMatKhau_LoiKhongTrungKhop {
            get {
                return ResourceManager.GetString("TextValidator_XacNhanMatKhau_LoiKhongTrungKhop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy thông tin tài khoản.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string ThongTinTaiKhoan_Loi_1 {
            get {
                return ResourceManager.GetString("ThongTinTaiKhoan_Loi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_add {
            get {
                object obj = ResourceManager.GetObject("user_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_delete_3 {
            get {
                object obj = ResourceManager.GetObject("user_delete_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_info_2 {
            get {
                object obj = ResourceManager.GetObject("user_info_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_info_2_64 {
            get {
                object obj = ResourceManager.GetObject("user_info_2_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video_x_generic {
            get {
                object obj = ResourceManager.GetObject("video_x_generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video_x_generic_2 {
            get {
                object obj = ResourceManager.GetObject("video_x_generic_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_calendar {
            get {
                object obj = ResourceManager.GetObject("view_calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_calendar_day_2 {
            get {
                object obj = ResourceManager.GetObject("view_calendar_day_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_refresh_4 {
            get {
                object obj = ResourceManager.GetObject("view_refresh_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_split_left_right_2 {
            get {
                object obj = ResourceManager.GetObject("view_split_left_right_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_split_top_bottom_2 {
            get {
                object obj = ResourceManager.GetObject("view_split_top_bottom_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong lúc lấy thông tin về thông báo.
        ///Nội dung lỗi: {0}.
        /// </summary>
        internal static string XemThongBao_Loi_NoiDung_1 {
            get {
                return ResourceManager.GetString("XemThongBao_Loi_NoiDung_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tải thông báo.
        /// </summary>
        internal static string XemThongBao_Loi_TieuDe {
            get {
                return ResourceManager.GetString("XemThongBao_Loi_TieuDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_3 {
            get {
                object obj = ResourceManager.GetObject("zoom_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
